spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nectar
    username: postgres
    password: password#2#2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
